% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Jul-2021 16:56:23
%  MATLAB version: 9.10.0.1684407 (R2021a) Update 3
% -------------------------------------------------------------------
saveVarsMat = load('ML_model_X.mat');

BaggedTreesX = saveVarsMat.BaggedTreesX; % <1x1 struct> unsupported class at BaggedTreesX.predictFcn

clear saveVarsMat;
